# Generated by Django 3.2.5 on 2022-04-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('authorname', models.CharField(
                    db_column='authorName',
                    max_length=200)),
            ],
            options={
                'db_table': 'author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publishdate', models.DateField(db_column='publishDate')),
                ('countpages', models.IntegerField(db_column='countPages')),
                ('picture', models.CharField(max_length=2048)),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookauthor',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
            ],
            options={
                'db_table': 'bookauthor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Isbnnumber',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('isbn', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'isbnnumber',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('langname', models.CharField(
                    db_column='langName',
                    max_length=50)),
            ],
            options={
                'db_table': 'language',
                'managed': False,
            },
        ),
    ]
